const courseData = [
  {
    id: 0,
    name: 'Adobe Premiere Pro CC: Complete Video Editing Masterclass',
    instructor: 'Mashuk Sarker Batista',
    price: 49,
    ratings: 4.3,
  },
  {
    id: 1,
    name: 'Complete web development course',
    instructor: 'Jhankar Mahbub',
    price: 57,
    ratings: 5,
  },
  {
    id: 2,
    name: 'Advanced CSS and Sass: Flexbox, Grid, Animations and More!',
    instructor: 'Jonas Schmedtmann',
    price: 49,
    ratings: 4.3,
  },
  {
    id: 3,
    name: 'Google Ads For Beginners 2020 - Step By Step Process',
    instructor: 'Joshua George',
    price: 23,
    ratings: 4.4,
  },
  {
    id: 4,
    name: 'AWS Certified Solutions Architect - Associate 2020',
    instructor: 'Mark Zuck',
    price: 45,
    ratings: 3.3,
  },
  {
    id: 5,
    name: 'The complete web development bootcamp',
    instructor: 'Bill Gates',
    price: 97,
    ratings: 4.3,
  },
  {
    id: 6,
    name: 'The complete Node JS bootcamp',
    instructor: 'Opu kazi',
    price: 50,
    ratings: 4.7,
  },
  {
    id: 7,
    name: 'The complete React Native bootcamp',
    instructor: 'Sorkar Mohiuddin',
    price: 49,
    ratings: 4.3,
  },
  {
    id: 8,
    name: 'How to Become an actor? ',
    instructor: 'Amir Khan',
    price: 29,
    ratings: 2.3,
  },
  {
    id: 9,
    name: 'How to Become a singer ?',
    instructor: 'Mahfuzur Rahman',
    price: 19,
    ratings: 4.5,
  },
  {
    id: 10,
    name: 'Ultimate driving course ',
    instructor: 'Hussanin Iqbal',
    price: 49,
    ratings: 4.3,
  },
  {
    id: 11,
    name: 'The complete front end development',
    instructor: 'Jasim Uddin',
    price: 99,
    ratings: 3.3,
  },
  {
    id: 12,
    name: 'The complete API course',
    instructor: 'Nazir',
    price: 69,
    ratings: 5.0,
  },
  {
    id: 13,
    name: 'The complete DevOps bootcamp',
    instructor: 'Asraful',
    price: 59,
    ratings: 4.9,
  },
  {
    id: 14,
    name: 'Ultimate CSS course',
    instructor: 'Amhamed Sani',
    price: 45,
    ratings: 4.0,
  },
];

export default courseData;
